// ============================================================
// Application Error Codes
// Every error code must be unique and descriptive.
// Frontend/clients can switch on these codes for specific handling.
// ============================================================

// ── Auth ──────────────────────────────────────────────────────
export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_ALREADY_USED: 'OTP_ALREADY_USED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  INVALID_FIELD_VALUE: 'INVALID_FIELD_VALUE',
  INVALID_PHONE_FORMAT: 'INVALID_PHONE_FORMAT',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  INVALID_DATE: 'INVALID_DATE',
  DATE_IN_PAST: 'DATE_IN_PAST',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  COMMITMENT_NOT_FOUND: 'COMMITMENT_NOT_FOUND',
  MILESTONE_NOT_FOUND: 'MILESTONE_NOT_FOUND',
  EVIDENCE_NOT_FOUND: 'EVIDENCE_NOT_FOUND',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  DISPUTE_NOT_FOUND: 'DISPUTE_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',

  // Conflicts
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  SLUG_ALREADY_EXISTS: 'SLUG_ALREADY_EXISTS',
  DUPLICATE_MEMBER: 'DUPLICATE_MEMBER',

  // Commitment State Machine
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  COMMITMENT_ALREADY_ACCEPTED: 'COMMITMENT_ALREADY_ACCEPTED',
  COMMITMENT_ALREADY_COMPLETED: 'COMMITMENT_ALREADY_COMPLETED',
  COMMITMENT_ALREADY_CANCELLED: 'COMMITMENT_ALREADY_CANCELLED',
  COMMITMENT_ALREADY_DISPUTED: 'COMMITMENT_ALREADY_DISPUTED',
  COMMITMENT_TERMINAL_STATE: 'COMMITMENT_TERMINAL_STATE',
  SYSTEM_ONLY_TRANSITION: 'SYSTEM_ONLY_TRANSITION',
  NOT_PARTICIPANT: 'NOT_PARTICIPANT',
  NOT_PROMISOR: 'NOT_PROMISOR',
  NOT_PROMISEE: 'NOT_PROMISEE',
  MILESTONE_DEPENDENCY_NOT_MET: 'MILESTONE_DEPENDENCY_NOT_MET',

  // Payments
  PAYMENT_INTENT_DUPLICATE: 'PAYMENT_INTENT_DUPLICATE',
  PAYMENT_INTENT_EXPIRED: 'PAYMENT_INTENT_EXPIRED',
  PAYMENT_INTENT_FAILED: 'PAYMENT_INTENT_FAILED',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_REPLAY_DETECTED: 'WEBHOOK_REPLAY_DETECTED',

  // Files & Media
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',

  // Trust & Verification
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  VERIFICATION_REJECTED: 'VERIFICATION_REJECTED',
  INSUFFICIENT_VERIFICATION_LEVEL: 'INSUFFICIENT_VERIFICATION_LEVEL',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_OTP_REQUESTS: 'TOO_MANY_OTP_REQUESTS',

  // Business Logic
  ACCOUNT_RESTRICTED: 'ACCOUNT_RESTRICTED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',

  // AI
  AI_CONFIRMATION_REQUIRED: 'AI_CONFIRMATION_REQUIRED',
  AI_CONFIRMATION_EXPIRED: 'AI_CONFIRMATION_EXPIRED',
  AI_PROPOSAL_INVALID: 'AI_PROPOSAL_INVALID',

  // System
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
